### PR TITLE
Breaking The Records Problem with solution added

### PR DESCRIPTION
**Pull request by shikhar8434**

### CODE REVIEW

**Comment by srsandy** [comment]
@shikhar8434 thank you for your contribution. Can you add your problem into a sub category folder that are present in Practice Problem folder

**Comment by shikhar8434** [comment]
Sure Sir I will

**Comment by shikhar8434** [comment]
Breaking The Records Added to SubCategory Arrays

**Comment by shikhar8434** [comment]
Kindly Merge it sir, I will contribute some more questions too

**Comment by srsandy** [comment]
@shikhar8434 one last thing. Capital R for Readme.md file

**Comment by shikhar8434** [comment]
Okay Sandeep , I am editing it

**Comment by srsandy** [comment]
@shikhar8434 if you would like to contribute more. I would recommend try book question. #34

**Pull request merged**
