### PR TITLE
Create WavePrintRowWise.java

### PR DESCRIPTION
**Pull request by arpitjain22june**

### CODE REVIEW

**Comment by arpitjain22june** [comment]
added a new program wave print row wise

**Comment by srsandy** [comment]
@arpitjain22june this is great that you are contributing to this repo. If you would like to contribute more. I would recommend try book question. #34

**Comment by srsandy** [comment]
I will check and accept your pr's soon.

**Comment by arpitjain22june** [comment]
@srsandy  sure i will check the book questions please accept my prs i am adding questions

**Comment by arpitjain22june** [comment]
it doesn't say hacktober fest accepted why?

**Pull request merged**
